language: node_js
node_js:
- 4
install:
  |
  npm install --registry http://registry.npmjs.org -g npm@latest
  npm --version
  npm install --registry http://registry.npmjs.org
script:
- npm run test-ci
